// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1LD3GVrnuZc5VEpJVkgAWyBn2i8wxJ7s',
    appId: '1:26893631499:web:1206bf843bc81c4479470e',
    messagingSenderId: '26893631499',
    projectId: 'groove-guru-8b76e',
    authDomain: 'groove-guru-8b76e.firebaseapp.com',
    databaseURL: 'https://groove-guru-8b76e-default-rtdb.firebaseio.com',
    storageBucket: 'groove-guru-8b76e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClDlOoHd8wIQMKM0tyKIlSLA-17MifT30',
    appId: '1:26893631499:android:3c205f176ea8fd2279470e',
    messagingSenderId: '26893631499',
    projectId: 'groove-guru-8b76e',
    databaseURL: 'https://groove-guru-8b76e-default-rtdb.firebaseio.com',
    storageBucket: 'groove-guru-8b76e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqMpV2-IWEkwR1gkQilEz0hb3bQlgt5QU',
    appId: '1:26893631499:ios:d62787bc101eb03479470e',
    messagingSenderId: '26893631499',
    projectId: 'groove-guru-8b76e',
    databaseURL: 'https://groove-guru-8b76e-default-rtdb.firebaseio.com',
    storageBucket: 'groove-guru-8b76e.appspot.com',
    iosBundleId: 'com.example.grooveGuruApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqMpV2-IWEkwR1gkQilEz0hb3bQlgt5QU',
    appId: '1:26893631499:ios:1379acddc5bf412279470e',
    messagingSenderId: '26893631499',
    projectId: 'groove-guru-8b76e',
    databaseURL: 'https://groove-guru-8b76e-default-rtdb.firebaseio.com',
    storageBucket: 'groove-guru-8b76e.appspot.com',
    iosBundleId: 'com.example.grooveGuruApp.RunnerTests',
  );
}
